import fs from "node:fs";
import path from "node:path";
import type { DatabaseSync } from "node:sqlite";
import { dataDir } from "../db.js";
import { loadProtectedPatterns } from "../scope/protected.js";

export const GRAPH_MD_NAME = "GRAPH.md";
const MAX_ROWS = 20;
const MAX_LINES = 160;

// Peta pengetahuan beku untuk agent: ringkasan graph yang dibatasi anggaran.
// BUKAN dump seluruh edge — file ini dimuat ke konteks, jadi tiap seksi
// di-cap agar repo 100 ribu edge tetap jadi ±150 baris.
export function buildGraphMd(db: DatabaseSync, repoRoot: string): string {
  const one = (sql: string): number => {
    try {
      return (db.prepare(sql).get() as { n: number }).n;
    } catch {
      return 0;
    }
  };
  const files = one(`SELECT COUNT(*) AS n FROM files`);
  const symbols = one(`SELECT COUNT(*) AS n FROM symbols`);
  const rels = one(`SELECT COUNT(*) AS n FROM relationships`);

  const lines: string[] = [
    `# Codebase Graph`,
    ``,
    `> Generated by \`scopecairn scan\`. Do not edit — regenerated when the graph changes.`,
    `> Visual map: open \`.scopecairn/GRAPH.html\` in a browser (offline, no dependencies).`,
    `> For task-specific context, run \`scopecairn context "<task>"\` instead of reading this whole file.`,
    ``,
    `## Stats`,
    ``,
    `- Files: ${files} | Symbols: ${symbols} | Relationships: ${rels}`,
    ``,
  ];

  // Peta modul.
  try {
    const mods = db
      .prepare(
        `SELECT CASE WHEN instr(path, '/') > 0 THEN substr(path, 1, instr(path, '/') - 1) ELSE '.' END AS mod,
                COUNT(*) AS n FROM files GROUP BY mod ORDER BY n DESC LIMIT ${MAX_ROWS}`
      )
      .all() as { mod: string; n: number }[];
    if (mods.length > 0) {
      lines.push(`## Modules`, ``);
      for (const m of mods) lines.push(`- ${m.mod}/ — ${m.n} files`);
      lines.push(``);
    }
  } catch {
    // ignore
  }

  // Simbol paling dipakai (jalur baca pertama).
  try {
    const top = db
      .prepare(
        `SELECT s.name, s.type, f.path AS file, COUNT(*) AS fanin
         FROM relationships r
         JOIN symbols s ON s.id = r.target_id
         JOIN files f ON f.id = s.file_id
         WHERE s.type IN ('function','class','method','component','interface','type')
         GROUP BY r.target_id ORDER BY fanin DESC LIMIT ${MAX_ROWS}`
      )
      .all() as { name: string; type: string; file: string; fanin: number }[];
    if (top.length > 0) {
      lines.push(`## Most-used symbols`, ``);
      for (const t of top) lines.push(`- ${t.name} (${t.type}, ${t.file}) ← ${t.fanin}x`);
      lines.push(``);
    }
  } catch {
    // ignore
  }

  // Rute + model dari adapter.
  const symList = (type: string, title: string): void => {
    try {
      const rows = db
        .prepare(
          `SELECT s.name, f.path AS file FROM symbols s
           JOIN files f ON f.id = s.file_id
           WHERE s.type = ? ORDER BY s.name LIMIT ${MAX_ROWS}`
        )
        .all(type) as { name: string; file: string }[];
      if (rows.length > 0) {
        lines.push(`## ${title}`, ``);
        for (const r of rows) lines.push(`- ${r.name} — ${r.file}`);
        lines.push(``);
      }
    } catch {
      // ignore
    }
  };
  symList("route", "Routes");
  symList("model", "Models");

  // Graphify Engine: simbol paling kritis (PageRank) bila metrik tersedia.
  try {
    const top = db
      .prepare(
        `SELECT s.name, s.type, f.path AS file, m.pagerank AS pr
         FROM node_metrics m
         JOIN symbols s ON s.id = m.node_id
         JOIN files f ON f.id = s.file_id
         ORDER BY m.pagerank DESC LIMIT 5`
      )
      .all() as { name: string; type: string; file: string; pr: number }[];
    if (top.length > 0) {
      lines.push(`## Critical hotspots (PageRank)`, ``);
      for (const t of top) lines.push(`- ${t.name} (${t.type}, ${t.file}) [pr=${t.pr.toFixed(4)}]`);
      lines.push(``);
    }
  } catch {
    // tabel metrik belum terisi — lewati
  }

  // Graphify Engine: peringatan siklus ketergantungan.
  try {
    const c = (db.prepare(`SELECT COUNT(*) AS n FROM cycles`).get() as { n: number }).n;
    if (c > 0) {
      lines.push(`## Circular dependencies`, ``);
      lines.push(`- ${c} dependency cycle(s) detected — see \`scopecairn doctor\`.`);
      lines.push(``);
    }
  } catch {
    // ignore
  }

  // Protected.
  try {
    const patterns = loadProtectedPatterns(repoRoot);
    if (patterns.length > 0) {
      lines.push(`## Protected (ask before touching)`, ``);
      for (const p of patterns.slice(0, MAX_ROWS)) lines.push(`- \`${p}\``);
      lines.push(``);
    }
  } catch {
    // ignore
  }

  const out = lines.join("\n");
  const trimmed = out.split("\n");
  if (trimmed.length > MAX_LINES) {
    return trimmed.slice(0, MAX_LINES).join("\n") + "\n";
  }
  return out;
}

export function graphMdPath(repoRoot: string): string {
  return path.join(dataDir(repoRoot), GRAPH_MD_NAME);
}

/** Tulis GRAPH.md bila graph berubah. Kembalikan true bila ditulis. */
export function writeGraphMdIfChanged(
  db: DatabaseSync,
  repoRoot: string,
  dirty: boolean
): boolean {
  if (!dirty) return false;
  try {
    fs.mkdirSync(dataDir(repoRoot), { recursive: true });
    fs.writeFileSync(graphMdPath(repoRoot), buildGraphMd(db, repoRoot));
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Graphify Engine — Fitur 5: multi-format exporter.
// mermaid (graph TD) · graphml (Gephi/Cytoscape) · dot (Graphviz) · json (AST).
// Anggaran default 500 node / 1500 edge agar output tetap terbaca; simbol
// diprioritaskan berdasar fan-in bila tabel node_metrics belum terisi.
// ---------------------------------------------------------------------------

export type ExportFormat = "mermaid" | "graphml" | "dot" | "json";

const EXPORT_NODE_CAP = 500;
const EXPORT_EDGE_CAP = 1500;

interface XNode {
  id: number;
  name: string;
  type: string;
  file: string;
}

interface XEdge {
  s: number;
  t: number;
  rel: string;
  w: number;
}

function readExportGraph(db: DatabaseSync): { nodes: XNode[]; edges: XEdge[] } {
  let nodes: XNode[] = [];
  try {
    // Prioritaskan simbol paling terhubung (fan-in + fan-out).
    nodes = db.prepare(
      `SELECT s.id, s.name, s.type, f.path AS file,
              (SELECT COUNT(*) FROM relationships r WHERE r.target_id = s.id) +
              (SELECT COUNT(*) FROM relationships r WHERE r.source_id = s.id) AS deg
       FROM symbols s JOIN files f ON f.id = s.file_id
       ORDER BY deg DESC LIMIT ${EXPORT_NODE_CAP}`
    ).all() as unknown as XNode[];
  } catch {
    try {
      nodes = db.prepare(
        `SELECT s.id, s.name, s.type, f.path AS file
         FROM symbols s JOIN files f ON f.id = s.file_id LIMIT ${EXPORT_NODE_CAP}`
      ).all() as unknown as XNode[];
    } catch {
      return { nodes: [], edges: [] };
    }
  }
  if (nodes.length === 0) return { nodes, edges: [] };
  const keep = new Set(nodes.map((n) => n.id));
  let edges: XEdge[] = [];
  try {
    edges = (
      db.prepare(
        `SELECT source_id AS s, target_id AS t, relationship_type AS rel,
                weight AS w FROM relationships LIMIT ${EXPORT_EDGE_CAP * 4}`
      ).all() as unknown as XEdge[]
    )
      .filter((e) => keep.has(e.s) && keep.has(e.t))
      .slice(0, EXPORT_EDGE_CAP);
  } catch {
    edges = [];
  }
  return { nodes, edges };
}

function escXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function mermaidId(n: number): string {
  return `n${n}`;
}

function mermaidLabel(n: XNode): string {
  return `${n.name} [${n.type}]`.replace(/["#<>`]/g, "").slice(0, 60);
}

/** Diagram Mermaid `graph TD` — cocok ditempel di PR/dokumentasi. */
export function exportMermaid(db: DatabaseSync): string {
  const { nodes, edges } = readExportGraph(db);
  const lines = ["graph TD"];
  for (const n of nodes) {
    lines.push(`    ${mermaidId(n.id)}["${mermaidLabel(n)}"]`);
  }
  for (const e of edges) {
    const rel = e.rel.replace(/[^A-Za-z0-9_]/g, "_").slice(0, 24) || "REL";
    lines.push(`    ${mermaidId(e.s)} -->|${rel}| ${mermaidId(e.t)}`);
  }
  return lines.join("\n") + "\n";
}

/** GraphML standar (Gephi / Cytoscape). */
export function exportGraphML(db: DatabaseSync): string {
  const { nodes, edges } = readExportGraph(db);
  const out = [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<graphml xmlns="http://graphml.graphdrawing.org/xmlns">`,
    `  <key id="name" for="node" attr.name="name" attr.type="string"/>`,
    `  <key id="type" for="node" attr.name="type" attr.type="string"/>`,
    `  <key id="file" for="node" attr.name="file" attr.type="string"/>`,
    `  <key id="rel" for="edge" attr.name="relationship" attr.type="string"/>`,
    `  <key id="weight" for="edge" attr.name="weight" attr.type="double"/>`,
    `  <graph id="scopecairn" edgedefault="directed">`,
  ];
  for (const n of nodes) {
    out.push(
      `    <node id="${mermaidId(n.id)}">` +
        `<data key="name">${escXml(n.name)}</data>` +
        `<data key="type">${escXml(n.type)}</data>` +
        `<data key="file">${escXml(n.file)}</data></node>`
    );
  }
  edges.forEach((e, i) => {
    out.push(
      `    <edge id="e${i}" source="${mermaidId(e.s)}" target="${mermaidId(e.t)}">` +
        `<data key="rel">${escXml(e.rel)}</data>` +
        `<data key="weight">${e.w}</data></edge>`
    );
  });
  out.push(`  </graph>`, `</graphml>`);
  return out.join("\n") + "\n";
}

/** Graphviz DOT — render ke PDF/PNG via `dot -Tpng`. */
export function exportDot(db: DatabaseSync): string {
  const { nodes, edges } = readExportGraph(db);
  const q = (s: string): string => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  const lines = [`digraph scopecairn {`, `  rankdir=LR;`, `  node [shape=box, style=rounded];`];
  for (const n of nodes) {
    lines.push(`  ${mermaidId(n.id)} [label=${q(`${n.name}\n(${n.type})`)}];`);
  }
  for (const e of edges) {
    lines.push(`  ${mermaidId(e.s)} -> ${mermaidId(e.t)} [label=${q(e.rel)}];`);
  }
  lines.push(`}`);
  return lines.join("\n") + "\n";
}

/** Graph JSON AST untuk integrasi skrip kustom. */
export function exportJson(db: DatabaseSync): string {
  const { nodes, edges } = readExportGraph(db);
  return (
    JSON.stringify(
      {
        generated_by: "scopecairn export",
        node_count: nodes.length,
        edge_count: edges.length,
        nodes: nodes.map((n) => ({ id: n.id, name: n.name, type: n.type, file: n.file })),
        edges: edges.map((e) => ({ source: e.s, target: e.t, relationship: e.rel, weight: e.w })),
      },
      null,
      2
    ) + "\n"
  );
}

export function exportGraph(db: DatabaseSync, format: ExportFormat): string {
  switch (format) {
    case "mermaid":
      return exportMermaid(db);
    case "graphml":
      return exportGraphML(db);
    case "dot":
      return exportDot(db);
    case "json":
      return exportJson(db);
  }
}
